# Generated by Django 2.2.3 on 2019-08-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('home', '0005_auto_20190803_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(default='Greg Meyer', max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
    ]
