# Generated by Django 2.2.3 on 2019-08-10 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0007_socialmediasettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='Your Facebook page URL'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.CharField(blank=True, help_text='Your Instagram username, without the @', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='youtube',
            field=models.URLField(blank=True, help_text='Your YouTube channel or user account URL'),
        ),
        migrations.CreateModel(
            name='SiteStyleSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_colour_theme', models.CharField(choices=[('5790D4', 'Blue'), ('56CF8C', 'Green'), ('925914', 'Rusty Red/Orange'), ('5A6978', 'Grey'), ('ffffff', 'None')], default='ffffff', help_text='Pick a colour', max_length=6)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
                ('site_banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
