# Generated by Django 2.2.3 on 2019-08-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190810_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitestylesettings',
            name='site_colour_theme',
            field=models.CharField(choices=[('87,144,212', 'Blue'), ('86,207,140', 'Green'), ('146,89,20', 'Rusty Red/Orange'), ('90,105,120', 'Grey'), ('255,255,255', 'None')], default='255,255,255', help_text='Pick a colour', max_length=11),
        ),
    ]
