# Generated by Django 2.2.3 on 2019-08-10 21:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0010_blogpage_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='twitter',
            field=models.CharField(blank=True, help_text='Your twitter handle, without the @', max_length=255),
        ),
        migrations.CreateModel(
            name='SiteFooterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_column', wagtail.core.fields.StreamField([('internal_link_left', wagtail.core.blocks.PageChooserBlock()), ('short_text', wagtail.core.blocks.CharBlock(max_length=300))])),
                ('middle_column', wagtail.core.fields.StreamField([('link_middle', wagtail.core.blocks.PageChooserBlock())])),
                ('right_column', wagtail.core.fields.StreamField([('internal_link_left', wagtail.core.blocks.PageChooserBlock()), ('short_text', wagtail.core.blocks.CharBlock(max_length=300))])),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
