# Generated by Django 2.2.3 on 2019-08-10 21:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190810_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefootersettings',
            name='left_column',
            field=wagtail.core.fields.StreamField([('internal_link_left', wagtail.core.blocks.PageChooserBlock()), ('short_text', wagtail.core.blocks.CharBlock(max_length=300)), ('external_document', wagtail.documents.blocks.DocumentChooserBlock())]),
        ),
    ]
