# Generated by Django 2.2.3 on 2019-08-11 05:21

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190811_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('dark_block_heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('subheading', wagtail.core.blocks.CharBlock(required=False))], classname='full title')), ('paragraph_text', wagtail.core.blocks.RichTextBlock()), ('article_preview', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title')), ('excerpt', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('link_page', wagtail.core.blocks.PageChooserBlock())])), ('words_and_images', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('video', wagtail.embeds.blocks.EmbedBlock()), ('three_column_content', wagtail.core.blocks.StructBlock([('first_column', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('second_column', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('third_column', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]))]))], blank=True),
        ),
    ]
