# Generated by Django 2.2.3 on 2019-08-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0019_homepage_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='bottom_left',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='bottom_right',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='top_left',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='top_right',
        ),
        migrations.AddField(
            model_name='homepage',
            name='ignore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_colour',
            field=models.CharField(choices=[('87,144,212', 'Blue'), ('86,207,140', 'Green'), ('146,89,20', 'Rusty Red/Orange'), ('90,105,120', 'Grey'), ('255,255,255', 'None')], default='255,255,255', help_text='Pick a colour', max_length=11),
        ),
    ]
