# Generated by Django 2.2.3 on 2019-08-11 11:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20190811_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='site',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='site_colour',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='site_image',
        ),
        migrations.RemoveField(
            model_name='sitestylesettings',
            name='site_banner_image',
        ),
        migrations.RemoveField(
            model_name='sitestylesettings',
            name='site_colour_theme',
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_styles',
            field=wagtail.core.fields.StreamField([('top_left_site', wagtail.core.blocks.StructBlock([('site_colour', wagtail.core.blocks.ChoiceBlock(choices=[('87,144,212', 'Blue'), ('86,207,140', 'Green'), ('146,89,20', 'Rusty Red/Orange'), ('90,105,120', 'Grey'), ('255,255,255', 'None')], help_text='Pick a colour')), ('site', wagtail.core.blocks.PageChooserBlock()), ('site_image', wagtail.images.blocks.ImageChooserBlock())])), ('top_rightt_site', wagtail.core.blocks.StructBlock([('site_colour', wagtail.core.blocks.ChoiceBlock(choices=[('87,144,212', 'Blue'), ('86,207,140', 'Green'), ('146,89,20', 'Rusty Red/Orange'), ('90,105,120', 'Grey'), ('255,255,255', 'None')], help_text='Pick a colour')), ('site', wagtail.core.blocks.PageChooserBlock()), ('site_image', wagtail.images.blocks.ImageChooserBlock())])), ('bottom_left_site', wagtail.core.blocks.StructBlock([('site_colour', wagtail.core.blocks.ChoiceBlock(choices=[('87,144,212', 'Blue'), ('86,207,140', 'Green'), ('146,89,20', 'Rusty Red/Orange'), ('90,105,120', 'Grey'), ('255,255,255', 'None')], help_text='Pick a colour')), ('site', wagtail.core.blocks.PageChooserBlock()), ('site_image', wagtail.images.blocks.ImageChooserBlock())])), ('bottom_right_site', wagtail.core.blocks.StructBlock([('site_colour', wagtail.core.blocks.ChoiceBlock(choices=[('87,144,212', 'Blue'), ('86,207,140', 'Green'), ('146,89,20', 'Rusty Red/Orange'), ('90,105,120', 'Grey'), ('255,255,255', 'None')], help_text='Pick a colour')), ('site', wagtail.core.blocks.PageChooserBlock()), ('site_image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True),
        ),
    ]
