# Generated by Django 2.2.3 on 2019-08-11 14:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20190811_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitestylesettings',
            name='style',
            field=wagtail.core.fields.StreamField([('styles', wagtail.core.blocks.StructBlock([('site_colour', wagtail.core.blocks.ChoiceBlock(choices=[('87,144,212', 'Blue'), ('86,207,140', 'Green'), ('146,89,20', 'Rusty Red/Orange'), ('90,105,120', 'Grey'), ('255,255,255', 'None')], help_text='Pick a colour')), ('site', wagtail.core.blocks.PageChooserBlock()), ('site_image', wagtail.images.blocks.ImageChooserBlock()), ('site_blurb', wagtail.core.blocks.RichTextBlock())]))], blank=True),
        ),
    ]
