# Generated by Django 2.2.3 on 2019-09-01 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0028_auto_20190901_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpage',
            name='site_style',
        ),
        migrations.AddField(
            model_name='standardpage',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
