# Generated by Django 2.2.3 on 2019-09-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20190901_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standardpage',
            old_name='site',
            new_name='overall_site',
        ),
    ]
