# Generated by Django 2.2.3 on 2019-09-01 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20190901_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='overall_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.StandardPage'),
        ),
    ]
