# Generated by Django 2.2.3 on 2019-09-01 17:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20190901_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='pages',
            field=wagtail.core.fields.StreamField([('site_subject', wagtail.core.blocks.PageChooserBlock())], blank=True),
        ),
    ]
