# Generated by Django 2.2.3 on 2019-09-08 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20190908_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='overall_site',
            field=models.ForeignKey(help_text='This sets the style for the heading of the page. So if you want an article under the Sports page, you can have the same heading for all sports pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.StandardPage'),
        ),
    ]
