# Generated by Django 2.2.3 on 2019-09-10 19:06

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20190908_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefootersettings',
            name='left_column',
            field=wagtail.core.fields.StreamField([('internal_link_block', wagtail.core.blocks.StructBlock([('internal_link', wagtail.core.blocks.PageChooserBlock()), ('link_text', wagtail.core.blocks.CharBlock(max_length=255))])), ('external_link_block', wagtail.core.blocks.StructBlock([('external_link', wagtail.core.blocks.URLBlock()), ('link_text', wagtail.core.blocks.CharBlock(max_length=255))])), ('short_text', wagtail.core.blocks.CharBlock(max_length=300)), ('external_document', wagtail.documents.blocks.DocumentChooserBlock()), ('contact_email', wagtail.core.blocks.StructBlock([('email', wagtail.core.blocks.EmailBlock()), ('email_text', wagtail.core.blocks.CharBlock(max_length=255))])), ('contact_phone_number', wagtail.core.blocks.StructBlock([('phone_number', wagtail.core.blocks.IntegerBlock()), ('phone_text', wagtail.core.blocks.CharBlock(max_length=255))]))]),
        ),
        migrations.AlterField(
            model_name='sitefootersettings',
            name='middle_column',
            field=wagtail.core.fields.StreamField([('internal_link_block', wagtail.core.blocks.StructBlock([('internal_link', wagtail.core.blocks.PageChooserBlock()), ('link_text', wagtail.core.blocks.CharBlock(max_length=255))])), ('external_link_block', wagtail.core.blocks.StructBlock([('external_link', wagtail.core.blocks.URLBlock()), ('link_text', wagtail.core.blocks.CharBlock(max_length=255))])), ('short_text', wagtail.core.blocks.CharBlock(max_length=300)), ('external_document', wagtail.documents.blocks.DocumentChooserBlock()), ('contact_email', wagtail.core.blocks.StructBlock([('email', wagtail.core.blocks.EmailBlock()), ('email_text', wagtail.core.blocks.CharBlock(max_length=255))])), ('contact_phone_number', wagtail.core.blocks.StructBlock([('phone_number', wagtail.core.blocks.IntegerBlock()), ('phone_text', wagtail.core.blocks.CharBlock(max_length=255))]))]),
        ),
        migrations.AlterField(
            model_name='sitefootersettings',
            name='right_column',
            field=wagtail.core.fields.StreamField([('internal_link_block', wagtail.core.blocks.StructBlock([('internal_link', wagtail.core.blocks.PageChooserBlock()), ('link_text', wagtail.core.blocks.CharBlock(max_length=255))])), ('external_link_block', wagtail.core.blocks.StructBlock([('external_link', wagtail.core.blocks.URLBlock()), ('link_text', wagtail.core.blocks.CharBlock(max_length=255))])), ('short_text', wagtail.core.blocks.CharBlock(max_length=300)), ('external_document', wagtail.documents.blocks.DocumentChooserBlock()), ('contact_email', wagtail.core.blocks.StructBlock([('email', wagtail.core.blocks.EmailBlock()), ('email_text', wagtail.core.blocks.CharBlock(max_length=255))])), ('contact_phone_number', wagtail.core.blocks.StructBlock([('phone_number', wagtail.core.blocks.IntegerBlock()), ('phone_text', wagtail.core.blocks.CharBlock(max_length=255))]))]),
        ),
    ]
