# Generated by Django 2.2.3 on 2019-09-10 19:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20190910_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('dark_block_heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('subheading', wagtail.core.blocks.CharBlock(required=False))], classname='full title')), ('paragraph_text', wagtail.core.blocks.RichTextBlock()), ('article_preview', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title')), ('excerpt', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(max_length=250))])), ('link_page', wagtail.core.blocks.PageChooserBlock())])), ('words_and_images', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(max_length=250))])), ('link_page', wagtail.core.blocks.PageChooserBlock(blank=True, required=False))])), ('video', wagtail.embeds.blocks.EmbedBlock()), ('three_column_content', wagtail.core.blocks.StructBlock([('first_column', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(max_length=250))])), ('link_page', wagtail.core.blocks.PageChooserBlock(blank=True, required=False))])), ('second_column', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(max_length=250))])), ('link_page', wagtail.core.blocks.PageChooserBlock(blank=True, required=False))])), ('third_column', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(max_length=250))])), ('link_page', wagtail.core.blocks.PageChooserBlock(blank=True, required=False))]))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='site_styles',
            field=wagtail.core.fields.StreamField([('one_site_area', wagtail.core.blocks.StructBlock([('site_colour', wagtail.core.blocks.ChoiceBlock(choices=[('87,144,212', 'Blue'), ('86,207,140', 'Green'), ('146,89,20', 'Rusty Red/Orange'), ('90,105,120', 'Grey'), ('255,255,255', 'None')], help_text='Pick a colour')), ('site', wagtail.core.blocks.PageChooserBlock()), ('site_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(max_length=250))])), ('site_blurb', wagtail.core.blocks.RichTextBlock())]))], blank=True),
        ),
        migrations.AlterField(
            model_name='sitestylesettings',
            name='style',
            field=wagtail.core.fields.StreamField([('styles', wagtail.core.blocks.StructBlock([('site_colour', wagtail.core.blocks.ChoiceBlock(choices=[('87,144,212', 'Blue'), ('86,207,140', 'Green'), ('146,89,20', 'Rusty Red/Orange'), ('90,105,120', 'Grey'), ('255,255,255', 'None')], help_text='Pick a colour')), ('site', wagtail.core.blocks.PageChooserBlock()), ('site_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(max_length=250))])), ('site_blurb', wagtail.core.blocks.RichTextBlock())]))], blank=True),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.core.fields.StreamField([('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(max_length=250))])), ('dark_block_heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('subheading', wagtail.core.blocks.CharBlock(required=False))], classname='full title')), ('paragraph_text', wagtail.core.blocks.RichTextBlock()), ('article_preview', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title')), ('excerpt', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(max_length=250))])), ('link_page', wagtail.core.blocks.PageChooserBlock())])), ('words_and_images', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(max_length=250))])), ('link_page', wagtail.core.blocks.PageChooserBlock(blank=True, required=False))])), ('video', wagtail.embeds.blocks.EmbedBlock()), ('three_column_content', wagtail.core.blocks.StructBlock([('first_column', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(max_length=250))])), ('link_page', wagtail.core.blocks.PageChooserBlock(blank=True, required=False))])), ('second_column', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(max_length=250))])), ('link_page', wagtail.core.blocks.PageChooserBlock(blank=True, required=False))])), ('third_column', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(max_length=250))])), ('link_page', wagtail.core.blocks.PageChooserBlock(blank=True, required=False))]))]))]),
        ),
    ]
